version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  manylinux2014-aarch64:
    parameters:
      cibw_build:
        type: string
        default: "cp37-*"

    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Install dependencies
          command: |
             sudo apt-get update && sudo apt-get -y install python3 python3-pip 
             export DEBIAN_FRONTEND=noninteractive && sudo apt-get install -y tzdata && sudo dpkg-reconfigure --frontend noninteractive tzdata
             sudo apt-get install libpq-dev -y libxml2-dev -y libxslt1-dev -y python3-dev -y
             sudo apt-get install gcc-aarch64-linux-gnu -y 
             python3 -m pip install backports.zoneinfo
             python3 -m pip install --upgrade pip wheel setuptools tox 
             python3 setup.py install 
             sudo apt install redis-server
             sudo service redis-server start 
             tox -e py38 
workflows:
  version: 2.1
  main:
    jobs:
      - manylinux2014-aarch64:
          matrix:
            parameters:
              cibw_build:
                - "cp37*"
