version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  manylinux2014-aarch64:
    parameters:
      cibw_build:
        type: string
        default: "cp37-*"

    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Install dependencies
          command: |
             apt-get update && apt-get -y install python3 python3-pip 
             ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && export DEBIAN_FRONTEND=noninteractive && apt-get install -y tzdata && dpkg-reconfigure --frontend noninteractive tzdata
             apt-get -y install software-properties-common && add-apt-repository ppa:deadsnakes/ppa && apt-get -y update
             apt install -y python3.8-venv && python3.8 -m venv venv38 && source venv38/bin/activate 
             python3.8 -m pip install --upgrade pip
             python3.8 --version 
             uname -m
             apt-get install libpq-dev -y libxml2-dev -y libxslt1-dev -y python3-dev -y
             apt-get install gcc-aarch64-linux-gnu -y 
             python3.8 -m pip install backports.zoneinfo
             python3.8 -m pip install --upgrade pip wheel setuptools tox 
             python3.8 setup.py install 
             apt install redis-server -y
             service redis-server start 
             tox -e py38 
workflows:
  version: 2.1
  main:
    jobs:
      - manylinux2014-aarch64:
          matrix:
            parameters:
              cibw_build:
                - "cp37*"
